name: "pull_request"

on: pull_request

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dfile.encoding=utf-8 -Dorg.gradle.jvmargs="-Xmx4g -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'macos-latest', 'ubuntu-latest', 'windows-latest' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v2.4.0
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Build
        if: matrix.os == 'macos-latest'
        run: ./gradlew build --no-daemon --stacktrace  --scan

      - name: Build
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew build --no-daemon --stacktrace  --scan

      - name: Build
        if: matrix.os == 'windows-latest'
        run: ./gradlew mingwX64Test --no-daemon --stacktrace --scan

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v2.2.4
        with:
          name: 'reports-${{ matrix.os }}'
          path: '**/build/reports/**'

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v2.2.4
        with:
          name: 'gradle-daemon-log'
          path: '/home/runner/.gradle/daemon/**'

  update_api:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v2.4.0
        with:
          distribution: 'temurin'
          java-version: 11

      - name: "Dump new API files"
        run: ./gradlew apiDump  --no-daemon  --scan

      - name: "Commit new API files"
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: Update API files
          file_pattern: arrow-libs/**/api/*.api
