name: "pull_request"

on: pull_request

env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.project.kotlin.incremental.multiplatform=false -Dorg.gradle.daemon=false -Dorg.gradle.project.kotlin.native.disableCompilerDaemon=true -Dorg.gradle.jvmargs="-Xmx6g -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'macos-latest', 'ubuntu-latest', 'windows-latest' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v2.4.0
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Build
        run: ./gradlew build

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v2.2.4
        with:
          name: 'reports-${{ matrix.os }}'
          path: '**/build/reports/**'

      - name: Stop Gradle daemons
        run: ./gradlew --stop

  update_api:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v2.4.0
        with:
          distribution: 'zulu'
          java-version: 11

      - name: "Dump new API files"
        run: ./gradlew apiDump

      - name: Stop Gradle daemons
        run: ./gradlew --stop

      - name: "Commit new API files"
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: Update API files
          file_pattern: arrow-libs/**/api/*.api
